[package]
name = "app"
version = "0.1.0"
authors = ["antiphoton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.2.2"
euclid = "0.20.7"
